# Generated by Django 4.0.6 on 2022-07-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_ide',
            new_name='post_id',
        ),
    ]
